// GENERATED-STYLE DATA — Bu dosya ülke listesini içerir.
// Yeni ülke eklemek/güncellemek için sadece bu listeyi düzenlemeniz yeterlidir.

part of 'core_country.dart';

/// Uygulamada kullanılabilecek tüm ülkelerin listesi.
///
/// Liste [CoreCountry.name] (İngilizce ad) alanına göre alfabetik sıralıdır.
const List<CoreCountry> kCoreCountries = <CoreCountry>[
  CoreCountry(isoCode: 'AF', dialCode: '93', name: 'Afghanistan', nameTr: 'Afganistan', mask: '## ### ####'),
  CoreCountry(isoCode: 'AL', dialCode: '355', name: 'Albania', nameTr: 'Arnavutluk', mask: '### ### ###'),
  CoreCountry(isoCode: 'DZ', dialCode: '213', name: 'Algeria', nameTr: 'Cezayir', mask: '### ### ###'),
  CoreCountry(isoCode: 'AS', dialCode: '1684', name: 'American Samoa', nameTr: 'Amerikan Samoası', mask: '### ####'),
  CoreCountry(isoCode: 'AD', dialCode: '376', name: 'Andorra', nameTr: 'Andorra', mask: '### ###'),
  CoreCountry(isoCode: 'AO', dialCode: '244', name: 'Angola', nameTr: 'Angola', mask: '### ### ###'),
  CoreCountry(isoCode: 'AI', dialCode: '1264', name: 'Anguilla', nameTr: 'Anguilla', mask: '### ####'),
  CoreCountry(isoCode: 'AG', dialCode: '1268', name: 'Antigua and Barbuda', nameTr: 'Antigua ve Barbuda', mask: '### ####'),
  CoreCountry(isoCode: 'AR', dialCode: '54', name: 'Argentina', nameTr: 'Arjantin', mask: '## #### ####'),
  CoreCountry(isoCode: 'AM', dialCode: '374', name: 'Armenia', nameTr: 'Ermenistan', mask: '## ### ###'),
  CoreCountry(isoCode: 'AW', dialCode: '297', name: 'Aruba', nameTr: 'Aruba', mask: '### ####'),
  CoreCountry(isoCode: 'AU', dialCode: '61', name: 'Australia', nameTr: 'Avustralya', mask: '### ### ###'),
  CoreCountry(isoCode: 'AT', dialCode: '43', name: 'Austria', nameTr: 'Avusturya', mask: '### ########'),
  CoreCountry(isoCode: 'AZ', dialCode: '994', name: 'Azerbaijan', nameTr: 'Azerbaycan', mask: '## ### ## ##'),
  CoreCountry(isoCode: 'BS', dialCode: '1242', name: 'Bahamas', nameTr: 'Bahamalar', mask: '### ####'),
  CoreCountry(isoCode: 'BH', dialCode: '973', name: 'Bahrain', nameTr: 'Bahreyn', mask: '#### ####'),
  CoreCountry(isoCode: 'BD', dialCode: '880', name: 'Bangladesh', nameTr: 'Bangladeş', mask: '### ### ####'),
  CoreCountry(isoCode: 'BB', dialCode: '1246', name: 'Barbados', nameTr: 'Barbados', mask: '### ####'),
  CoreCountry(isoCode: 'BY', dialCode: '375', name: 'Belarus', nameTr: 'Belarus', mask: '## ### ## ##'),
  CoreCountry(isoCode: 'BE', dialCode: '32', name: 'Belgium', nameTr: 'Belçika', mask: '### ## ## ##'),
  CoreCountry(isoCode: 'BZ', dialCode: '501', name: 'Belize', nameTr: 'Belize', mask: '### ####'),
  CoreCountry(isoCode: 'BJ', dialCode: '229', name: 'Benin', nameTr: 'Benin', mask: '#### ####'),
  CoreCountry(isoCode: 'BM', dialCode: '1441', name: 'Bermuda', nameTr: 'Bermuda', mask: '### ####'),
  CoreCountry(isoCode: 'BT', dialCode: '975', name: 'Bhutan', nameTr: 'Butan', mask: '#### ####'),
  CoreCountry(isoCode: 'BO', dialCode: '591', name: 'Bolivia', nameTr: 'Bolivya', mask: '#### ####'),
  CoreCountry(isoCode: 'BA', dialCode: '387', name: 'Bosnia and Herzegovina', nameTr: 'Bosna Hersek', mask: '#### ####'),
  CoreCountry(isoCode: 'BW', dialCode: '267', name: 'Botswana', nameTr: 'Botsvana', mask: '#### ####'),
  CoreCountry(isoCode: 'BR', dialCode: '55', name: 'Brazil', nameTr: 'Brezilya', mask: '## ##### ####'),
  CoreCountry(isoCode: 'VG', dialCode: '1284', name: 'British Virgin Islands', nameTr: 'Britanya Virjin Adaları', mask: '### ####'),
  CoreCountry(isoCode: 'BN', dialCode: '673', name: 'Brunei', nameTr: 'Brunei', mask: '### ####'),
  CoreCountry(isoCode: 'BG', dialCode: '359', name: 'Bulgaria', nameTr: 'Bulgaristan', mask: '### ### ###'),
  CoreCountry(isoCode: 'BF', dialCode: '226', name: 'Burkina Faso', nameTr: 'Burkina Faso', mask: '#### ####'),
  CoreCountry(isoCode: 'BI', dialCode: '257', name: 'Burundi', nameTr: 'Burundi', mask: '#### ####'),
  CoreCountry(isoCode: 'KH', dialCode: '855', name: 'Cambodia', nameTr: 'Kamboçya', mask: '### ### ###'),
  CoreCountry(isoCode: 'CM', dialCode: '237', name: 'Cameroon', nameTr: 'Kamerun', mask: '### ### ###'),
  CoreCountry(isoCode: 'CA', dialCode: '1', name: 'Canada', nameTr: 'Kanada', mask: '### ### ####'),
  CoreCountry(isoCode: 'CV', dialCode: '238', name: 'Cape Verde', nameTr: 'Cape Verde', mask: '### ####'),
  CoreCountry(isoCode: 'KY', dialCode: '1345', name: 'Cayman Islands', nameTr: 'Cayman Adaları', mask: '### ####'),
  CoreCountry(isoCode: 'CF', dialCode: '236', name: 'Central African Republic', nameTr: 'Orta Afrika Cumhuriyeti', mask: '#### ####'),
  CoreCountry(isoCode: 'TD', dialCode: '235', name: 'Chad', nameTr: 'Çad', mask: '#### ####'),
  CoreCountry(isoCode: 'CL', dialCode: '56', name: 'Chile', nameTr: 'Şili', mask: '# #### ####'),
  CoreCountry(isoCode: 'CN', dialCode: '86', name: 'China', nameTr: 'Çin', mask: '### #### ####'),
  CoreCountry(isoCode: 'CO', dialCode: '57', name: 'Colombia', nameTr: 'Kolombiya', mask: '### ### ####'),
  CoreCountry(isoCode: 'KM', dialCode: '269', name: 'Comoros', nameTr: 'Komorlar', mask: '### ####'),
  CoreCountry(isoCode: 'CG', dialCode: '242', name: 'Congo', nameTr: 'Kongo', mask: '### ### ###'),
  CoreCountry(isoCode: 'CD', dialCode: '243', name: 'Congo (DRC)', nameTr: 'Demokratik Kongo Cumhuriyeti', mask: '### ### ###'),
  CoreCountry(isoCode: 'CK', dialCode: '682', name: 'Cook Islands', nameTr: 'Cook Adaları', mask: '## ###'),
  CoreCountry(isoCode: 'CR', dialCode: '506', name: 'Costa Rica', nameTr: 'Kosta Rika', mask: '#### ####'),
  CoreCountry(isoCode: 'CI', dialCode: '225', name: "Cote d'Ivoire", nameTr: 'Fildişi Sahili', mask: '### ### ####'),
  CoreCountry(isoCode: 'HR', dialCode: '385', name: 'Croatia', nameTr: 'Hırvatistan', mask: '## ### ####'),
  CoreCountry(isoCode: 'CU', dialCode: '53', name: 'Cuba', nameTr: 'Küba', mask: '#### ####'),
  CoreCountry(isoCode: 'CW', dialCode: '599', name: 'Curacao', nameTr: 'Curaçao', mask: '### ####'),
  CoreCountry(isoCode: 'CY', dialCode: '357', name: 'Cyprus', nameTr: 'Kıbrıs', mask: '## ### ###'),
  CoreCountry(isoCode: 'CZ', dialCode: '420', name: 'Czechia', nameTr: 'Çekya', mask: '### ### ###'),
  CoreCountry(isoCode: 'DK', dialCode: '45', name: 'Denmark', nameTr: 'Danimarka', mask: '## ## ## ##'),
  CoreCountry(isoCode: 'DJ', dialCode: '253', name: 'Djibouti', nameTr: 'Cibuti', mask: '#### ####'),
  CoreCountry(isoCode: 'DM', dialCode: '1767', name: 'Dominica', nameTr: 'Dominika', mask: '### ####'),
  CoreCountry(isoCode: 'DO', dialCode: '1809', name: 'Dominican Republic', nameTr: 'Dominik Cumhuriyeti', mask: '### ####'),
  CoreCountry(isoCode: 'EC', dialCode: '593', name: 'Ecuador', nameTr: 'Ekvador', mask: '### ### ###'),
  CoreCountry(isoCode: 'EG', dialCode: '20', name: 'Egypt', nameTr: 'Mısır', mask: '## #### ####'),
  CoreCountry(isoCode: 'SV', dialCode: '503', name: 'El Salvador', nameTr: 'El Salvador', mask: '#### ####'),
  CoreCountry(isoCode: 'GQ', dialCode: '240', name: 'Equatorial Guinea', nameTr: 'Ekvator Ginesi', mask: '### ### ###'),
  CoreCountry(isoCode: 'ER', dialCode: '291', name: 'Eritrea', nameTr: 'Eritre', mask: '### ####'),
  CoreCountry(isoCode: 'EE', dialCode: '372', name: 'Estonia', nameTr: 'Estonya', mask: '#### ####'),
  CoreCountry(isoCode: 'SZ', dialCode: '268', name: 'Eswatini', nameTr: 'Esvatini', mask: '#### ####'),
  CoreCountry(isoCode: 'ET', dialCode: '251', name: 'Ethiopia', nameTr: 'Etiyopya', mask: '### ### ###'),
  CoreCountry(isoCode: 'FO', dialCode: '298', name: 'Faroe Islands', nameTr: 'Faroe Adaları', mask: '### ###'),
  CoreCountry(isoCode: 'FJ', dialCode: '679', name: 'Fiji', nameTr: 'Fiji', mask: '### ####'),
  CoreCountry(isoCode: 'FI', dialCode: '358', name: 'Finland', nameTr: 'Finlandiya', mask: '## ### ## ###'),
  CoreCountry(isoCode: 'FR', dialCode: '33', name: 'France', nameTr: 'Fransa', mask: '# ## ## ## ##'),
  CoreCountry(isoCode: 'GF', dialCode: '594', name: 'French Guiana', nameTr: 'Fransız Guyanası', mask: '### ### ###'),
  CoreCountry(isoCode: 'PF', dialCode: '689', name: 'French Polynesia', nameTr: 'Fransız Polinezyası', mask: '#### ####'),
  CoreCountry(isoCode: 'GA', dialCode: '241', name: 'Gabon', nameTr: 'Gabon', mask: '#### ####'),
  CoreCountry(isoCode: 'GM', dialCode: '220', name: 'Gambia', nameTr: 'Gambiya', mask: '### ####'),
  CoreCountry(isoCode: 'GE', dialCode: '995', name: 'Georgia', nameTr: 'Gürcistan', mask: '### ## ## ##'),
  CoreCountry(isoCode: 'DE', dialCode: '49', name: 'Germany', nameTr: 'Almanya', mask: '#### #######'),
  CoreCountry(isoCode: 'GH', dialCode: '233', name: 'Ghana', nameTr: 'Gana', mask: '### ### ###'),
  CoreCountry(isoCode: 'GI', dialCode: '350', name: 'Gibraltar', nameTr: 'Cebelitarık', mask: '#### ####'),
  CoreCountry(isoCode: 'GR', dialCode: '30', name: 'Greece', nameTr: 'Yunanistan', mask: '### ### ####'),
  CoreCountry(isoCode: 'GL', dialCode: '299', name: 'Greenland', nameTr: 'Grönland', mask: '### ###'),
  CoreCountry(isoCode: 'GD', dialCode: '1473', name: 'Grenada', nameTr: 'Grenada', mask: '### ####'),
  CoreCountry(isoCode: 'GP', dialCode: '590', name: 'Guadeloupe', nameTr: 'Guadeloupe', mask: '### ### ###'),
  CoreCountry(isoCode: 'GU', dialCode: '1671', name: 'Guam', nameTr: 'Guam', mask: '### ####'),
  CoreCountry(isoCode: 'GT', dialCode: '502', name: 'Guatemala', nameTr: 'Guatemala', mask: '#### ####'),
  CoreCountry(isoCode: 'GN', dialCode: '224', name: 'Guinea', nameTr: 'Gine', mask: '### ### ###'),
  CoreCountry(isoCode: 'GW', dialCode: '245', name: 'Guinea-Bissau', nameTr: 'Gine-Bissau', mask: '### ### ###'),
  CoreCountry(isoCode: 'GY', dialCode: '592', name: 'Guyana', nameTr: 'Guyana', mask: '### ####'),
  CoreCountry(isoCode: 'HT', dialCode: '509', name: 'Haiti', nameTr: 'Haiti', mask: '#### ####'),
  CoreCountry(isoCode: 'HN', dialCode: '504', name: 'Honduras', nameTr: 'Honduras', mask: '#### ####'),
  CoreCountry(isoCode: 'HK', dialCode: '852', name: 'Hong Kong', nameTr: 'Hong Kong', mask: '#### ####'),
  CoreCountry(isoCode: 'HU', dialCode: '36', name: 'Hungary', nameTr: 'Macaristan', mask: '## ### ####'),
  CoreCountry(isoCode: 'IS', dialCode: '354', name: 'Iceland', nameTr: 'İzlanda', mask: '### ####'),
  CoreCountry(isoCode: 'IN', dialCode: '91', name: 'India', nameTr: 'Hindistan', mask: '##### #####'),
  CoreCountry(isoCode: 'ID', dialCode: '62', name: 'Indonesia', nameTr: 'Endonezya', mask: '### #### ####'),
  CoreCountry(isoCode: 'IR', dialCode: '98', name: 'Iran', nameTr: 'İran', mask: '### ### ####'),
  CoreCountry(isoCode: 'IQ', dialCode: '964', name: 'Iraq', nameTr: 'Irak', mask: '### ### ####'),
  CoreCountry(isoCode: 'IE', dialCode: '353', name: 'Ireland', nameTr: 'İrlanda', mask: '## ### ####'),
  CoreCountry(isoCode: 'IL', dialCode: '972', name: 'Israel', nameTr: 'İsrail', mask: '## ### ####'),
  CoreCountry(isoCode: 'IT', dialCode: '39', name: 'Italy', nameTr: 'İtalya', mask: '### ### ####'),
  CoreCountry(isoCode: 'JM', dialCode: '1876', name: 'Jamaica', nameTr: 'Jamaika', mask: '### ####'),
  CoreCountry(isoCode: 'JP', dialCode: '81', name: 'Japan', nameTr: 'Japonya', mask: '## #### ####'),
  CoreCountry(isoCode: 'JO', dialCode: '962', name: 'Jordan', nameTr: 'Ürdün', mask: '### ### ###'),
  CoreCountry(isoCode: 'KZ', dialCode: '7', name: 'Kazakhstan', nameTr: 'Kazakistan', mask: '### ### ## ##'),
  CoreCountry(isoCode: 'KE', dialCode: '254', name: 'Kenya', nameTr: 'Kenya', mask: '### ######'),
  CoreCountry(isoCode: 'KI', dialCode: '686', name: 'Kiribati', nameTr: 'Kiribati', mask: '## ###'),
  CoreCountry(isoCode: 'XK', dialCode: '383', name: 'Kosovo', nameTr: 'Kosova', mask: '#### ####'),
  CoreCountry(isoCode: 'KW', dialCode: '965', name: 'Kuwait', nameTr: 'Kuveyt', mask: '#### ####'),
  CoreCountry(isoCode: 'KG', dialCode: '996', name: 'Kyrgyzstan', nameTr: 'Kırgızistan', mask: '### ### ###'),
  CoreCountry(isoCode: 'LA', dialCode: '856', name: 'Laos', nameTr: 'Laos', mask: '### ### ###'),
  CoreCountry(isoCode: 'LV', dialCode: '371', name: 'Latvia', nameTr: 'Letonya', mask: '#### ####'),
  CoreCountry(isoCode: 'LB', dialCode: '961', name: 'Lebanon', nameTr: 'Lübnan', mask: '#### ####'),
  CoreCountry(isoCode: 'LS', dialCode: '266', name: 'Lesotho', nameTr: 'Lesotho', mask: '#### ####'),
  CoreCountry(isoCode: 'LR', dialCode: '231', name: 'Liberia', nameTr: 'Liberya', mask: '#### ####'),
  CoreCountry(isoCode: 'LY', dialCode: '218', name: 'Libya', nameTr: 'Libya', mask: '### ### ###'),
  CoreCountry(isoCode: 'LI', dialCode: '423', name: 'Liechtenstein', nameTr: 'Lihtenştayn', mask: '### ####'),
  CoreCountry(isoCode: 'LT', dialCode: '370', name: 'Lithuania', nameTr: 'Litvanya', mask: '#### ####'),
  CoreCountry(isoCode: 'LU', dialCode: '352', name: 'Luxembourg', nameTr: 'Lüksemburg', mask: '### ### ###'),
  CoreCountry(isoCode: 'MO', dialCode: '853', name: 'Macao', nameTr: 'Makao', mask: '#### ####'),
  CoreCountry(isoCode: 'MG', dialCode: '261', name: 'Madagascar', nameTr: 'Madagaskar', mask: '### ### ###'),
  CoreCountry(isoCode: 'MW', dialCode: '265', name: 'Malawi', nameTr: 'Malavi', mask: '### ### ###'),
  CoreCountry(isoCode: 'MY', dialCode: '60', name: 'Malaysia', nameTr: 'Malezya', mask: '## ### ####'),
  CoreCountry(isoCode: 'MV', dialCode: '960', name: 'Maldives', nameTr: 'Maldivler', mask: '### ####'),
  CoreCountry(isoCode: 'ML', dialCode: '223', name: 'Mali', nameTr: 'Mali', mask: '#### ####'),
  CoreCountry(isoCode: 'MT', dialCode: '356', name: 'Malta', nameTr: 'Malta', mask: '#### ####'),
  CoreCountry(isoCode: 'MH', dialCode: '692', name: 'Marshall Islands', nameTr: 'Marshall Adaları', mask: '### ####'),
  CoreCountry(isoCode: 'MQ', dialCode: '596', name: 'Martinique', nameTr: 'Martinik', mask: '### ### ###'),
  CoreCountry(isoCode: 'MR', dialCode: '222', name: 'Mauritania', nameTr: 'Moritanya', mask: '#### ####'),
  CoreCountry(isoCode: 'MU', dialCode: '230', name: 'Mauritius', nameTr: 'Mauritius', mask: '#### ####'),
  CoreCountry(isoCode: 'MX', dialCode: '52', name: 'Mexico', nameTr: 'Meksika', mask: '### ### ####'),
  CoreCountry(isoCode: 'FM', dialCode: '691', name: 'Micronesia', nameTr: 'Mikronezya', mask: '### ####'),
  CoreCountry(isoCode: 'MD', dialCode: '373', name: 'Moldova', nameTr: 'Moldova', mask: '#### ####'),
  CoreCountry(isoCode: 'MC', dialCode: '377', name: 'Monaco', nameTr: 'Monako', mask: '#### ####'),
  CoreCountry(isoCode: 'MN', dialCode: '976', name: 'Mongolia', nameTr: 'Moğolistan', mask: '#### ####'),
  CoreCountry(isoCode: 'ME', dialCode: '382', name: 'Montenegro', nameTr: 'Karadağ', mask: '#### ####'),
  CoreCountry(isoCode: 'MS', dialCode: '1664', name: 'Montserrat', nameTr: 'Montserrat', mask: '### ####'),
  CoreCountry(isoCode: 'MA', dialCode: '212', name: 'Morocco', nameTr: 'Fas', mask: '### ### ###'),
  CoreCountry(isoCode: 'MZ', dialCode: '258', name: 'Mozambique', nameTr: 'Mozambik', mask: '### ### ###'),
  CoreCountry(isoCode: 'MM', dialCode: '95', name: 'Myanmar', nameTr: 'Myanmar', mask: '### ### ###'),
  CoreCountry(isoCode: 'NA', dialCode: '264', name: 'Namibia', nameTr: 'Namibya', mask: '### ### ###'),
  CoreCountry(isoCode: 'NR', dialCode: '674', name: 'Nauru', nameTr: 'Nauru', mask: '### ####'),
  CoreCountry(isoCode: 'NP', dialCode: '977', name: 'Nepal', nameTr: 'Nepal', mask: '### ### ####'),
  CoreCountry(isoCode: 'NL', dialCode: '31', name: 'Netherlands', nameTr: 'Hollanda', mask: '# ########'),
  CoreCountry(isoCode: 'NC', dialCode: '687', name: 'New Caledonia', nameTr: 'Yeni Kaledonya', mask: '### ###'),
  CoreCountry(isoCode: 'NZ', dialCode: '64', name: 'New Zealand', nameTr: 'Yeni Zelanda', mask: '## ### ####'),
  CoreCountry(isoCode: 'NI', dialCode: '505', name: 'Nicaragua', nameTr: 'Nikaragua', mask: '#### ####'),
  CoreCountry(isoCode: 'NE', dialCode: '227', name: 'Niger', nameTr: 'Nijer', mask: '#### ####'),
  CoreCountry(isoCode: 'NG', dialCode: '234', name: 'Nigeria', nameTr: 'Nijerya', mask: '### ### ####'),
  CoreCountry(isoCode: 'KP', dialCode: '850', name: 'North Korea', nameTr: 'Kuzey Kore', mask: '### ### ####'),
  CoreCountry(isoCode: 'MK', dialCode: '389', name: 'North Macedonia', nameTr: 'Kuzey Makedonya', mask: '#### ####'),
  CoreCountry(isoCode: 'MP', dialCode: '1670', name: 'Northern Mariana Islands', nameTr: 'Kuzey Mariana Adaları', mask: '### ####'),
  CoreCountry(isoCode: 'NO', dialCode: '47', name: 'Norway', nameTr: 'Norveç', mask: '### ## ###'),
  CoreCountry(isoCode: 'OM', dialCode: '968', name: 'Oman', nameTr: 'Umman', mask: '#### ####'),
  CoreCountry(isoCode: 'PK', dialCode: '92', name: 'Pakistan', nameTr: 'Pakistan', mask: '### #######'),
  CoreCountry(isoCode: 'PW', dialCode: '680', name: 'Palau', nameTr: 'Palau', mask: '### ####'),
  CoreCountry(isoCode: 'PS', dialCode: '970', name: 'Palestine', nameTr: 'Filistin', mask: '### ### ###'),
  CoreCountry(isoCode: 'PA', dialCode: '507', name: 'Panama', nameTr: 'Panama', mask: '#### ####'),
  CoreCountry(isoCode: 'PG', dialCode: '675', name: 'Papua New Guinea', nameTr: 'Papua Yeni Gine', mask: '#### ####'),
  CoreCountry(isoCode: 'PY', dialCode: '595', name: 'Paraguay', nameTr: 'Paraguay', mask: '### ### ###'),
  CoreCountry(isoCode: 'PE', dialCode: '51', name: 'Peru', nameTr: 'Peru', mask: '### ### ###'),
  CoreCountry(isoCode: 'PH', dialCode: '63', name: 'Philippines', nameTr: 'Filipinler', mask: '### ### ####'),
  CoreCountry(isoCode: 'PL', dialCode: '48', name: 'Poland', nameTr: 'Polonya', mask: '### ### ###'),
  CoreCountry(isoCode: 'PT', dialCode: '351', name: 'Portugal', nameTr: 'Portekiz', mask: '### ### ###'),
  CoreCountry(isoCode: 'PR', dialCode: '1787', name: 'Puerto Rico', nameTr: 'Porto Riko', mask: '### ####'),
  CoreCountry(isoCode: 'QA', dialCode: '974', name: 'Qatar', nameTr: 'Katar', mask: '#### ####'),
  CoreCountry(isoCode: 'RE', dialCode: '262', name: 'Reunion', nameTr: 'Réunion', mask: '### ### ###'),
  CoreCountry(isoCode: 'RO', dialCode: '40', name: 'Romania', nameTr: 'Romanya', mask: '### ### ###'),
  CoreCountry(isoCode: 'RU', dialCode: '7', name: 'Russia', nameTr: 'Rusya', mask: '### ### ## ##'),
  CoreCountry(isoCode: 'RW', dialCode: '250', name: 'Rwanda', nameTr: 'Ruanda', mask: '### ### ###'),
  CoreCountry(isoCode: 'KN', dialCode: '1869', name: 'Saint Kitts and Nevis', nameTr: 'Saint Kitts ve Nevis', mask: '### ####'),
  CoreCountry(isoCode: 'LC', dialCode: '1758', name: 'Saint Lucia', nameTr: 'Saint Lucia', mask: '### ####'),
  CoreCountry(isoCode: 'VC', dialCode: '1784', name: 'Saint Vincent and the Grenadines', nameTr: 'Saint Vincent ve Grenadinler', mask: '### ####'),
  CoreCountry(isoCode: 'WS', dialCode: '685', name: 'Samoa', nameTr: 'Samoa', mask: '### ####'),
  CoreCountry(isoCode: 'SM', dialCode: '378', name: 'San Marino', nameTr: 'San Marino', mask: '### ### ####'),
  CoreCountry(isoCode: 'ST', dialCode: '239', name: 'Sao Tome and Principe', nameTr: 'São Tomé ve Príncipe', mask: '### ####'),
  CoreCountry(isoCode: 'SA', dialCode: '966', name: 'Saudi Arabia', nameTr: 'Suudi Arabistan', mask: '## ### ####'),
  CoreCountry(isoCode: 'SN', dialCode: '221', name: 'Senegal', nameTr: 'Senegal', mask: '### ### ###'),
  CoreCountry(isoCode: 'RS', dialCode: '381', name: 'Serbia', nameTr: 'Sırbistan', mask: '## ### ####'),
  CoreCountry(isoCode: 'SC', dialCode: '248', name: 'Seychelles', nameTr: 'Seyşeller', mask: '### ####'),
  CoreCountry(isoCode: 'SL', dialCode: '232', name: 'Sierra Leone', nameTr: 'Sierra Leone', mask: '#### ####'),
  CoreCountry(isoCode: 'SG', dialCode: '65', name: 'Singapore', nameTr: 'Singapur', mask: '#### ####'),
  CoreCountry(isoCode: 'SX', dialCode: '1721', name: 'Sint Maarten', nameTr: 'Sint Maarten', mask: '### ####'),
  CoreCountry(isoCode: 'SK', dialCode: '421', name: 'Slovakia', nameTr: 'Slovakya', mask: '### ### ###'),
  CoreCountry(isoCode: 'SI', dialCode: '386', name: 'Slovenia', nameTr: 'Slovenya', mask: '#### ####'),
  CoreCountry(isoCode: 'SB', dialCode: '677', name: 'Solomon Islands', nameTr: 'Solomon Adaları', mask: '### ####'),
  CoreCountry(isoCode: 'SO', dialCode: '252', name: 'Somalia', nameTr: 'Somali', mask: '#### ####'),
  CoreCountry(isoCode: 'ZA', dialCode: '27', name: 'South Africa', nameTr: 'Güney Afrika', mask: '## ### ####'),
  CoreCountry(isoCode: 'KR', dialCode: '82', name: 'South Korea', nameTr: 'Güney Kore', mask: '## #### ####'),
  CoreCountry(isoCode: 'SS', dialCode: '211', name: 'South Sudan', nameTr: 'Güney Sudan', mask: '### ### ###'),
  CoreCountry(isoCode: 'ES', dialCode: '34', name: 'Spain', nameTr: 'İspanya', mask: '### ## ## ##'),
  CoreCountry(isoCode: 'LK', dialCode: '94', name: 'Sri Lanka', nameTr: 'Sri Lanka', mask: '### ### ###'),
  CoreCountry(isoCode: 'SD', dialCode: '249', name: 'Sudan', nameTr: 'Sudan', mask: '### ### ###'),
  CoreCountry(isoCode: 'SR', dialCode: '597', name: 'Suriname', nameTr: 'Surinam', mask: '### ####'),
  CoreCountry(isoCode: 'SE', dialCode: '46', name: 'Sweden', nameTr: 'İsveç', mask: '## ### ## ##'),
  CoreCountry(isoCode: 'CH', dialCode: '41', name: 'Switzerland', nameTr: 'İsviçre', mask: '## ### ## ##'),
  CoreCountry(isoCode: 'SY', dialCode: '963', name: 'Syria', nameTr: 'Suriye', mask: '### ### ###'),
  CoreCountry(isoCode: 'TW', dialCode: '886', name: 'Taiwan', nameTr: 'Tayvan', mask: '### ### ###'),
  CoreCountry(isoCode: 'TJ', dialCode: '992', name: 'Tajikistan', nameTr: 'Tacikistan', mask: '## ### ####'),
  CoreCountry(isoCode: 'TZ', dialCode: '255', name: 'Tanzania', nameTr: 'Tanzanya', mask: '### ### ###'),
  CoreCountry(isoCode: 'TH', dialCode: '66', name: 'Thailand', nameTr: 'Tayland', mask: '## ### ####'),
  CoreCountry(isoCode: 'TL', dialCode: '670', name: 'Timor-Leste', nameTr: 'Doğu Timor', mask: '#### ####'),
  CoreCountry(isoCode: 'TG', dialCode: '228', name: 'Togo', nameTr: 'Togo', mask: '#### ####'),
  CoreCountry(isoCode: 'TO', dialCode: '676', name: 'Tonga', nameTr: 'Tonga', mask: '### ####'),
  CoreCountry(isoCode: 'TT', dialCode: '1868', name: 'Trinidad and Tobago', nameTr: 'Trinidad ve Tobago', mask: '### ####'),
  CoreCountry(isoCode: 'TN', dialCode: '216', name: 'Tunisia', nameTr: 'Tunus', mask: '#### ####'),
  CoreCountry(isoCode: 'TR', dialCode: '90', name: 'Turkiye', nameTr: 'Türkiye', mask: '### ### ## ##'),
  CoreCountry(isoCode: 'TM', dialCode: '993', name: 'Turkmenistan', nameTr: 'Türkmenistan', mask: '## ## ## ##'),
  CoreCountry(isoCode: 'TC', dialCode: '1649', name: 'Turks and Caicos Islands', nameTr: 'Turks ve Caicos Adaları', mask: '### ####'),
  CoreCountry(isoCode: 'TV', dialCode: '688', name: 'Tuvalu', nameTr: 'Tuvalu', mask: '### ###'),
  CoreCountry(isoCode: 'VI', dialCode: '1340', name: 'U.S. Virgin Islands', nameTr: 'ABD Virjin Adaları', mask: '### ####'),
  CoreCountry(isoCode: 'UG', dialCode: '256', name: 'Uganda', nameTr: 'Uganda', mask: '### ### ###'),
  CoreCountry(isoCode: 'UA', dialCode: '380', name: 'Ukraine', nameTr: 'Ukrayna', mask: '## ### ## ##'),
  CoreCountry(isoCode: 'AE', dialCode: '971', name: 'United Arab Emirates', nameTr: 'Birleşik Arap Emirlikleri', mask: '## ### ####'),
  CoreCountry(isoCode: 'GB', dialCode: '44', name: 'United Kingdom', nameTr: 'Birleşik Krallık', mask: '#### ######'),
  CoreCountry(isoCode: 'US', dialCode: '1', name: 'United States', nameTr: 'Amerika Birleşik Devletleri', mask: '### ### ####'),
  CoreCountry(isoCode: 'UY', dialCode: '598', name: 'Uruguay', nameTr: 'Uruguay', mask: '#### ####'),
  CoreCountry(isoCode: 'UZ', dialCode: '998', name: 'Uzbekistan', nameTr: 'Özbekistan', mask: '## ### ## ##'),
  CoreCountry(isoCode: 'VU', dialCode: '678', name: 'Vanuatu', nameTr: 'Vanuatu', mask: '### ####'),
  CoreCountry(isoCode: 'VA', dialCode: '379', name: 'Vatican City', nameTr: 'Vatikan', mask: '### ### ####'),
  CoreCountry(isoCode: 'VE', dialCode: '58', name: 'Venezuela', nameTr: 'Venezuela', mask: '### ### ####'),
  CoreCountry(isoCode: 'VN', dialCode: '84', name: 'Vietnam', nameTr: 'Vietnam', mask: '## ### ## ##'),
  CoreCountry(isoCode: 'YE', dialCode: '967', name: 'Yemen', nameTr: 'Yemen', mask: '### ### ###'),
  CoreCountry(isoCode: 'ZM', dialCode: '260', name: 'Zambia', nameTr: 'Zambiya', mask: '### ### ###'),
  CoreCountry(isoCode: 'ZW', dialCode: '263', name: 'Zimbabwe', nameTr: 'Zimbabve', mask: '### ### ###'),
];
